import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync } from 'node:fs';
import { createServer } from 'node:http';
import path from 'node:path';
import { test } from 'node:test';
import { _electron as electron, type ElectronApplication } from 'playwright';

test('desktop creates assets, runs real workflows, opens report and restores history', { timeout: 180_000 }, async () => {
  const root = process.cwd();
  mkdirSync('artifacts', { recursive: true });
  const data = mkdtempSync(path.resolve('artifacts/desktop-'));
  const server = createServer((_req, res) => {
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.end('<html><head><title>Local test</title></head><body><h1>Testing Workspace</h1><p>Real browser verification</p></body></html>');
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const address = server.address();
  assert.ok(address && typeof address !== 'string');
  const baseUrl = `http://127.0.0.1:${address.port}`;
  const env: Record<string, string> = { ...Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => entry[1] !== undefined && entry[0] !== 'ELECTRON_RUN_AS_NODE')), WORKSPACE_DATA_DIR: path.join(data, 'app'), WORKSPACE_PROJECTS_DIR: path.join(data, 'projects') };
  let application: ElectronApplication | undefined;
  try {
    application = await electron.launch({ args: [root], env, timeout: 45_000 });
    const page = await application.firstWindow();
    const uiErrors: string[] = [];
    page.on('pageerror', (e) => uiErrors.push(e.message));
    await page.getByRole('button', { name: '新建项目', exact: true }).click();
    await page.getByLabel('项目名称', { exact: true }).fill('未保存草稿');
    await page.keyboard.press('Escape');
    await page.getByRole('dialog').waitFor({ state: 'hidden' });
    assert.equal((await page.evaluate(() => window.workspace.state())).projects.length, 0);
    await page.getByRole('button', { name: '新建项目', exact: true }).click();
    await page.getByRole('button', { name: '保存', exact: true }).focus();
    await page.keyboard.press('Tab');
    assert.ok(await page.getByRole('dialog').evaluate((dialog) => dialog.contains(document.activeElement)));
    await page.getByLabel('项目名称', { exact: true }).fill('LongbridgeAI');
    await page.getByLabel('项目描述', { exact: true }).fill('Web、Android 和 iOS 的业务测试 · 本地演示');
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('heading', { name: 'Test Cases' }).waitFor();
    await page.getByRole('button', { name: '新建 Suite' }).click();
    await page.getByLabel('Suite 名称', { exact: true }).fill('Chat');
    await page.getByLabel('Suite 名称', { exact: true }).press('Enter');
    await page.getByRole('button', { name: '新建用例', exact: true }).first().click();
    await page.getByLabel('用例名称', { exact: true }).fill('Send message while logged out');
    await page.getByRole('checkbox', { name: 'Android' }).check();
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('heading', { name: 'Send message while logged out' }).waitFor();
    await page.getByRole('button', { name: '编辑用例', exact: true }).click();
    await page.getByLabel('业务描述', { exact: true }).fill('验证匿名用户打开聊天页面后，页面正常显示。当前 Workflow 使用本地页面验证执行链路，不调用 AI。');
    await page.getByLabel('优先级', { exact: true }).selectOption('P0');
    await page.getByLabel('标签（用逗号分隔）', { exact: true }).fill('chat, smoke, anonymous');
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('button', { name: 'Environments', exact: true }).click();
    await page.getByRole('button', { name: '编辑', exact: true }).click();
    await page.getByLabel('Web 地址', { exact: true }).fill(baseUrl);
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('button', { name: /^Test Cases/ }).click();
    await page.getByRole('button', { name: /Send message while logged out/ }).click();
    await page.locator('[data-testid="workflow-row"]').filter({ hasText: 'Android' }).getByRole('button', { name: '导入 YAML' }).click();
    await page.getByLabel('Workflow YAML', { exact: true }).fill('cases:\n  - name: Mobile draft\n    steps:\n      - launch: {package: com.example.app}\n');
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByText('Workflow 已保存，移动端执行尚未接入', { exact: true }).waitFor({ timeout: 5_000 });
    assert.equal(await page.locator('[data-testid="workflow-row"]').filter({ hasText: 'Android' }).getByRole('button', { name: '运行', exact: true }).count(), 0);
    await page.getByRole('button', { name: '导入 YAML', exact: true }).first().click();
    // Only the operating-system file picker is substituted; the app reads and validates the real file.
    await application.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, path.join(root, 'tests/fixtures/passed.yaml'));
    await page.getByRole('button', { name: '从文件导入', exact: true }).click();
    await page.waitForFunction(() => document.querySelector<HTMLTextAreaElement>('textarea[name="yaml"]')?.value.includes('recordToReport'));
    assert.match(await page.getByLabel('Workflow YAML', { exact: true }).inputValue(), /recordToReport/);
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('button', { name: '运行', exact: true }).click();
    await page.getByRole('button', { name: '打开 Midscene 报告', exact: true }).waitFor({ timeout: 45_000 });
    await page.locator('[data-testid="run-summary"] [data-status="passed"]').waitFor({ timeout: 45_000 });
    await page.getByRole('tab', { name: '运行事件', exact: true }).click();
    assert.match(await page.getByRole('tabpanel').innerText(), /recordToReport/);
    await page.getByRole('tab', { name: '运行事件', exact: true }).press('ArrowLeft');
    await page.getByTestId('run-step').first().waitFor();
    await page.screenshot({ path: path.join(root, 'artifacts/desktop-run.png') });
    const reportPromise = application.waitForEvent('window');
    await page.getByRole('button', { name: '打开 Midscene 报告', exact: true }).click();
    const report = await reportPromise;
    await report.getByText('Screenshot', { exact: true }).click();
    await report.getByText('JSON View', { exact: true }).click();
    await report.getByText('Copy JSON', { exact: false }).waitFor();
    await report.close();
    await page.getByRole('button', { name: '返回用例再运行' }).click();
    await page.getByRole('heading', { name: 'Send message while logged out', exact: true }).waitFor();
    await page.screenshot({ path: path.join(root, 'artifacts/desktop-case.png'), animations: 'disabled' });
    await page.locator('[data-testid="workflow-row"]').filter({ hasText: 'Web' }).getByRole('button', { name: '查看 / 编辑', exact: true }).click();
    await page.getByLabel('Workflow YAML', { exact: true }).fill('cases:\n  - name: Invalid\n    steps:\n      - notRegistered: fail\n');
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: /notRegistered/ }).waitFor();
    await page.getByLabel('Workflow YAML', { exact: true }).fill(readFileSync('tests/fixtures/cancelled.yaml', 'utf8'));
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('button', { name: '运行', exact: true }).click();
    await page.locator('[data-testid="run-step"] strong').filter({ hasText: /^wait$/ }).waitFor({ timeout: 45_000 });
    const duplicateError = await page.evaluate(async () => {
      const state = await window.workspace.state();
      const p = state.projects[0]!, c = p.cases[0]!;
      try { await window.workspace.run({ projectId: p.id, caseId: c.id, workflowId: c.workflows.find((w) => w.platform === 'web')!.id, environmentId: p.environments[0]!.id }); }
      catch (error) { return String(error); }
      return '';
    });
    assert.match(duplicateError, /已有测试正在运行/);
    await page.getByRole('button', { name: '取消运行', exact: true }).click();
    await page.locator('[data-testid="run-summary"] [data-status="cancelled"]').waitFor({ timeout: 30_000 });
    await page.getByRole('button', { name: /^Test Cases/ }).click();
    await page.getByLabel('搜索用例', { exact: true }).fill('anonymous');
    await page.getByRole('button', { name: /Send message while logged out/ }).waitFor();
    await page.getByLabel('搜索用例', { exact: true }).fill('no-match');
    await page.getByRole('heading', { name: '没有找到匹配的用例' }).waitFor();
    await page.getByLabel('搜索用例', { exact: true }).fill('');
    await page.screenshot({ path: path.join(root, 'artifacts/desktop-cases.png') });
    await page.getByRole('button', { name: 'Model Settings', exact: true }).click();
    await page.getByLabel('模型名称', { exact: true }).fill('local-test-model');
    await page.getByLabel('服务地址', { exact: true }).fill('https://model.example.invalid/v1');
    await page.getByLabel('模型系列', { exact: true }).fill('qwen3-vl');
    const syntheticKey = 'synthetic-desktop-test-key-not-a-real-credential';
    await page.getByLabel(/^API Key/).fill(syntheticKey);
    await page.getByRole('button', { name: '保存模型配置', exact: true }).click();
    await page.getByText('模型配置已保存', { exact: true }).waitFor();
    const savedModel = readFileSync(path.join(data, 'app/model.json'), 'utf8');
    assert.ok(!savedModel.includes(syntheticKey));
    assert.ok(JSON.parse(savedModel).encryptedKey);
    assert.equal(await page.getByLabel(/^API Key/).inputValue(), '');
    await page.getByRole('button', { name: '保存模型配置', exact: true }).click();
    assert.equal(JSON.parse(readFileSync(path.join(data, 'app/model.json'), 'utf8')).encryptedKey, JSON.parse(savedModel).encryptedKey);
    assert.equal(uiErrors.length, 0, uiErrors.join('\n'));
    await application.close();
    application = await electron.launch({ args: [root], env, timeout: 45_000 });
    const restored = await application.firstWindow();
    await restored.getByRole('button', { name: /LongbridgeAI.*本地演示/ }).click();
    await restored.getByRole('button', { name: /Send message while logged out/ }).waitFor();
    await restored.getByRole('button', { name: 'Run History', exact: true }).click();
    assert.equal(await restored.locator('[data-testid="run-row"]').count(), 2);
    assert.equal(await restored.locator('[data-testid="run-row"] [data-status="cancelled"]').count(), 1);
    assert.equal(await restored.locator('[data-testid="run-row"] [data-status="passed"]').count(), 1);
    await restored.getByRole('button', { name: /^Projects/ }).click();
    await restored.screenshot({ path: path.join(root, 'artifacts/desktop-projects.png') });
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]!.setSize(980, 680));
    await restored.waitForFunction(() => window.innerWidth <= 980);
    assert.ok(await restored.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await restored.screenshot({ path: path.join(root, 'artifacts/desktop-compact.png') });
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]!.setSize(1380, 900));
    await restored.getByRole('button', { name: 'Model Settings', exact: true }).click();
    assert.equal(await restored.getByLabel('模型名称', { exact: true }).inputValue(), 'local-test-model');
    assert.equal(await restored.getByLabel('服务地址', { exact: true }).inputValue(), 'https://model.example.invalid/v1');
    assert.equal(await restored.getByLabel(/^API Key/).inputValue(), '');
    await restored.locator('[data-testid="saved-key"]').getByText('已保存', { exact: true }).waitFor();
    console.log(`Desktop data: ${data}`);
  } catch (error) {
    const page = application?.windows()[0];
    if (page && !page.isClosed()) {
      console.log((await page.locator('body').innerText()).slice(0,6000));
      await page.screenshot({ path: path.join(root, 'artifacts/desktop-failure.png') });
    }
    throw error;
  } finally {
    await application?.close(); server.closeAllConnections();
    await new Promise<void>((resolve) => server.close(() => resolve()));
  }
});
