import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync } from 'node:fs';
import { createServer } from 'node:http';
import path from 'node:path';
import { test } from 'node:test';
import { expect } from '@playwright/test';
import { _electron as electron, type ElectronApplication } from 'playwright';

test('real desktop imports, reviews, restores, saves and trials Markdown without recording or a model', { timeout: 180000 }, async () => {
  mkdirSync('artifacts', { recursive: true });
  const directory = mkdtempSync(path.resolve('artifacts/document-import-ui-'));
  let fail = false, clicks = 0;
  const server = createServer((request, response) => {
    if (request.url === '/submit') { clicks++; response.end(fail ? '错误结果' : '完成'); return; }
    response.setHeader('content-type', 'text/html; charset=utf-8');
    response.end('<button onclick="fetch(\'/submit\').then(r=>r.text()).then(t=>document.querySelector(\'p\').textContent=t)">提交</button><p>尚未提交</p>');
  });
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  const address = server.address(); assert.ok(address && typeof address !== 'string');
  const environment = { ...Object.fromEntries(Object.entries(process.env).filter((item): item is [string, string] => item[1] !== undefined && item[0] !== 'ELECTRON_RUN_AS_NODE')), WORKSPACE_DATA_DIR: path.join(directory, 'app'), WORKSPACE_PROJECTS_DIR: path.join(directory, 'projects') };
  for (const key of Object.keys(environment)) if (/^(MIDSCENE_MODEL|OPENAI_)/.test(key)) delete (environment as any)[key];
  let app: ElectronApplication | undefined;
  try {
    app = await electron.launch({ args: [process.cwd()], env: environment });
    let page = await app.firstWindow(); page.setDefaultTimeout(15000);
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
    await page.getByRole('button', { name: '新建项目', exact: true }).click();
    await page.getByLabel('项目名称', { exact: true }).fill('文档导入本地验证');
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('button', { name: '知识库', exact: true }).click();
    await page.getByRole('button', { name: '添加知识', exact: true }).click();
    await page.getByLabel(/^知识名称 /).fill('Agent 列表');
    await page.getByLabel('知识别名 Agent 列表').fill('我的 Agent, agent列表');
    await page.getByLabel('知识内容 Agent 列表').fill('从首页点击我的 Agent，再等待 Agent 列表标题出现。');
    await page.getByLabel('知识状态 Agent 列表').selectOption('confirmed');
    await page.getByRole('button', { name: '保存知识库', exact: true }).click();
    await expect(page.getByText('知识库已保存', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Environments', exact: true }).click();
    await page.getByRole('button', { name: '编辑', exact: true }).click();
    await page.getByLabel('Web 地址', { exact: true }).fill(`http://127.0.0.1:${address.port}`);
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.getByRole('button', { name: /^Test Cases/ }).click();
    await page.getByRole('button', { name: '从文档生成', exact: true }).click();
    await expect(page.getByLabel('文档导入模式')).toHaveValue('existing');
    await page.getByLabel('Markdown 文档').fill('# 本地模块\n\n## [LOCAL-001] 提交完成\n- 前置条件：打开 ${baseUrl}\n- 步骤：\n  1. 点击文本“提交”\n- 预期结果：\n  - 页面显示“完成”\n\n## [LOCAL-002] 不完整用例\n- 步骤：\n  1. 点击文本“提交”\n');
    await page.getByRole('button', { name: '解析 Markdown', exact: true }).click();
    await page.getByLabel('候选用例标题').fill('提交完成（人工审查）');
    await page.getByLabel('选择用例 不完整用例', { exact: true }).uncheck();
    await page.getByRole('button', { name: '不完整用例', exact: true }).click();
    await expect(page.getByText(/生成前需补充：没有预期结果/)).toBeVisible();
    await page.getByRole('button', { name: '提交完成（人工审查）', exact: true }).click();
    await page.getByRole('button', { name: '保存导入草稿', exact: true }).click();
    await expect(page.getByText('草稿已保存，重启后可继续处理。', { exact: true })).toBeVisible();
    await page.screenshot({ path: path.join(directory, 'review.png'), fullPage: true });
    await app.close(); app = await electron.launch({ args: [process.cwd()], env: environment });
    page = await app.firstWindow(); page.setDefaultTimeout(15000); page.on('pageerror', error => errors.push(error.message));
    await page.getByRole('button', { name: /文档导入本地验证/ }).click();
    await page.getByRole('button', { name: '从文档生成', exact: true }).click();
    await page.getByRole('button', { name: 'pasted.md · 2 条用例', exact: true }).click();
    await expect(page.getByLabel('候选用例标题')).toHaveValue('提交完成（人工审查）');
    await page.getByRole('button', { name: '生成选中的 Workflow', exact: true }).click();
    await expect(page.getByTestId('workflow-editor')).toBeVisible();
    await page.getByLabel('步骤名称 2', { exact: true }).fill('提交操作已人工检查');
    await page.getByRole('button', { name: '生成选中的 Workflow', exact: true }).click();
    await expect(page.getByRole('button', { name: '确认覆盖选中的 Workflow 并重新生成', exact: true })).toBeVisible();
    await expect(page.getByLabel('步骤名称 2', { exact: true })).toHaveValue('提交操作已人工检查');
    await page.getByRole('button', { name: '保存选中测试资产', exact: true }).click();
    await expect(page.getByText(/已保存 1 条用例/)).toBeVisible();
    const state = await page.evaluate(() => window.workspace.state());
    assert.equal(state.projects[0]!.cases.length, 1);
    assert.equal(clicks, 0, 'import/generation/save must not touch the browser');
    await page.getByRole('button', { name: '配置选中用例的试跑', exact: true }).click();
    await expect(page.getByTestId('import-validation-status')).toContainText('待验证');
    await page.getByRole('button', { name: '运行', exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('此次试跑会真实操作页面');
    await expect(page.getByRole('dialog')).toContainText('将执行准备：打开 ${baseUrl}');
    await expect(page.getByRole('dialog')).toContainText('按文本点击：提交');
    await page.screenshot({ path: path.join(directory, 'trial-preview.png') });
    await page.getByRole('button', { name: '确认并启动试跑', exact: true }).click();
    await expect(page.locator('[data-status="passed"]').first()).toBeVisible({ timeout: 30000 });
    assert.equal(clicks, 1);
    const passed = (await page.evaluate(() => window.workspace.state())).runs[0]!;
    assert.equal(passed.status, 'passed');
    await page.screenshot({ path: path.join(directory, 'passed.png') });
    await page.getByRole('button', { name: /^Test Cases/ }).click();
    await page.getByRole('button', { name: /提交完成（人工审查）/ }).click();
    await expect(page.getByTestId('import-validation-status')).toContainText('当前版本与配置验证通过');
    fail = true;
    await page.getByRole('button', { name: '运行', exact: true }).click();
    await page.getByRole('button', { name: '确认并启动试跑', exact: true }).click();
    await expect(page.locator('[data-status="failed"]').first()).toBeVisible({ timeout: 30000 });
    assert.equal(clicks, 2);
    await page.screenshot({ path: path.join(directory, 'failed.png') });
    const failed = (await page.evaluate(() => window.workspace.state())).runs[0]!;
    assert.equal(failed.status, 'failed');
    const result = await page.evaluate(id => window.workspace.runDetail({ runId: id }), failed.runId);
    assert.ok(result.events.some(event => event.type === 'step-finished' && event.node === 'click_by_text' && event.status === 'success'));
    assert.ok(result.events.some(event => event.type === 'step-finished' && event.node === 'assertText' && event.status === 'failed'));
    const project = state.projects[0]!, item = project.cases[0]!;
    const source = JSON.parse(readFileSync(path.join(project.root, project.suites.find(suite => suite.id === item.suiteId)!.directory, item.id, 'source.json'), 'utf8'));
    assert.equal(source.spec.title, '提交完成（人工审查）');
    assert.equal(source.spec.expectations[0].text, '页面显示“完成”');
    const knowledge = await page.evaluate(projectId => window.workspace.knowledge({ projectId }), project.id);
    assert.equal(knowledge.entries[0]!.status, 'confirmed');
    assert.deepEqual(knowledge.entries[0]!.aliases, ['我的 Agent', 'agent列表']);
    await page.getByRole('button', { name: /^Test Cases/ }).click();
    await page.getByRole('button', { name: '从文档生成', exact: true }).click();
    await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, path.resolve('tests/fixtures/document-import/login.xmind'));
    await page.getByRole('button', { name: '上传 .md / .xmind', exact: true }).click();
    await expect(page.getByLabel('候选用例标题')).toHaveValue('密码错误不能登录');
    await expect(page.getByText('节点 case-login', { exact: true })).toBeVisible();
    await expect(page.getByLabel('前置条件类型 1')).toHaveValue('check');
    await page.getByRole('button', { name: '保存导入草稿', exact: true }).click();
    await expect(page.getByText('草稿已保存，重启后可继续处理。', { exact: true })).toBeVisible();
    assert.equal(clicks, 2, 'XMind import must not touch the browser');
    await page.screenshot({ path: path.join(directory, 'xmind-review.png'), fullPage: true });
    await page.getByRole('button', { name: '从中间拆分用例', exact: true }).click();
    await expect(page.getByRole('button', { name: '密码错误不能登录（拆分）', exact: true })).toBeVisible();
    await page.getByRole('button', { name: '保存导入草稿', exact: true }).click();
    await expect(page.getByText('草稿已保存，重启后可继续处理。', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: '合并勾选的用例', exact: true }).click();
    await expect(page.getByLabel('用例步骤 3', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: '保存导入草稿', exact: true }).click();
    await expect(page.getByText('草稿已保存，重启后可继续处理。', { exact: true })).toBeVisible();
    assert.deepEqual(errors, []);
  } finally { await app?.close(); await new Promise<void>(resolve => server.close(() => resolve())); }
});
