import { useEffect, useRef, useState } from 'react';
import { FileUp, Save, Sparkles, Square } from 'lucide-react';
import type { CaseIssue, CaseSpec, ImportDraft, ImportDraftSnapshot, ParsedImport, SourceNode } from '../shared/case-spec.js';
import { splitCaseSpec, mergeCaseSpecs } from '../shared/case-spec-edit.js';
import type { Project } from '../shared/workspace.js';
import { WorkflowEditor } from './WorkflowEditor.js';
import { VariableEditor } from './VariableEditor.js';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Badge } from '@/components/ui/badge';

const originLabel = (origin: CaseSpec['origin']) => ({ source: '原文', ai: 'AI 建议', manual: '人工编辑' })[origin];
const sourceLabel = (spec: CaseSpec) => spec.ref.nodeId ? `节点 ${spec.ref.nodeId}` : `第 ${spec.ref.line ?? 1}–${spec.ref.endLine ?? spec.ref.line ?? 1} 行`;
function SourceTree({ nodes, depth = 0 }: { nodes: SourceNode[]; depth?: number }) {
  return <ul className="space-y-2 border-l pl-3 text-xs">{nodes.map(node => <li key={node.id}>{node.children.length ? <details open={depth < 3}><summary className="cursor-pointer break-words">{node.title} <span className="text-muted-foreground">({node.id})</span></summary><div className="mt-2"><SourceTree nodes={node.children} depth={depth + 1} /></div></details> : <p className="break-words">{node.title} <span className="text-muted-foreground">({node.id})</span></p>}</li>)}</ul>;
}
export function DocumentImportView({ project, onTrial }: { project: Project; onTrial(ids: string[]): void }) {
  const [text, setText] = useState(''), [mode, setMode] = useState<'existing' | 'design'>('existing');
  const [suiteId, setSuiteId] = useState(project.suites[0]?.id ?? ''), [newSuiteName, setNewSuiteName] = useState('');
  const [draft, setDraft] = useState<ImportDraft>(), [revision, setRevision] = useState('');
  const [savedDrafts, setSavedDrafts] = useState<ImportDraftSnapshot[]>([]), [selected, setSelected] = useState('');
  const [stage, setStage] = useState<'import' | 'review' | 'workflow'>('import');
  const [issues, setIssues] = useState<Record<string, CaseIssue[]>>({}), [busy, setBusy] = useState('');
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [confirmGenerate, setConfirmGenerate] = useState<'plan' | 'compile'>();
  const [duplicate, setDuplicate] = useState<'skip' | 'copy'>('skip'), [variablesValid, setVariablesValid] = useState(true);
  const [workflowValidity, setWorkflowValidity] = useState<Record<string, boolean>>({});
  const request = useRef<string | undefined>(undefined), alive = useRef(true);
  useEffect(() => { alive.current = true; void window.workspace.listImportDrafts({ projectId: project.id }).then(setSavedDrafts).catch(cause => setError(String(cause))); return () => { alive.current = false; if (request.current) void window.workspace.cancelImportPlan({ requestId: request.current }); }; }, [project.id]);
  async function act(label: string, work: () => Promise<void>) { setError(''); setNotice(''); setBusy(label); try { await work(); } catch (cause) { if (alive.current) setError(String(cause)); } finally { if (alive.current) setBusy(''); } }
  function accept(parsed: ParsedImport) {
    const value: ImportDraft = { id: crypto.randomUUID(), document: parsed.document, mode, cases: mode === 'design' ? [] : parsed.cases, selectedIds: mode === 'design' ? [] : parsed.cases.map(spec => spec.id), workflows: {}, variables: {}, suiteId: suiteId === 'new' ? '' : suiteId, ...(suiteId === 'new' ? { newSuiteName } : {}), saved: {} };
    setDraft(value); setRevision(''); setSelected(value.cases[0]?.id ?? ''); setIssues({}); setStage('review');
    if (parsed.needsAI || mode === 'design') setNotice('请使用 AI 识别或设计候选用例，然后逐条审查。');
  }
  useEffect(() => {
    if (!draft) return;
    let live = true;
    const timer = setTimeout(() => { void window.workspace.compileImportCases({ projectId: project.id, cases: draft.cases, variables: draft.variables }).then(result => { if (live) setIssues(result.issues); }).catch(cause => { if (live) setError(String(cause)); }); }, 250);
    return () => { live = false; clearTimeout(timer); };
  }, [JSON.stringify(draft?.cases), JSON.stringify(draft?.variables), project.assets?.revision]);
  const spec = draft?.cases.find(item => item.id === selected);
  const patch = (change: Partial<CaseSpec>) => setDraft(current => current ? { ...current, cases: current.cases.map(item => item.id === selected ? { ...item, ...change, origin: 'manual' } : item) } : current);
  async function persist(value = draft!) { const ids = new Set(value.cases.map(item => item.id)); value = { ...value, workflows: Object.fromEntries(Object.entries(value.workflows).filter(([id]) => ids.has(id))), saved: Object.fromEntries(Object.entries(value.saved).filter(([id]) => ids.has(id))) }; const result = await window.workspace.saveImportDraft({ projectId: project.id, draft: value, revision }); setDraft(result.draft); setRevision(result.revision); return result; }
  async function generate() {
    if (!draft) return;
    await act('正在编译选中用例', async () => {
      const result = await window.workspace.compileImportCases({ projectId: project.id, cases: draft.cases.filter(item => draft.selectedIds.includes(item.id)), variables: draft.variables });
      const next = { ...draft, workflows: { ...draft.workflows, ...result.workflows } };
      setDraft(next); setIssues(result.issues); setConfirmGenerate(undefined); setStage('workflow'); await persist(next);
      setNotice(`已生成 ${Object.keys(result.workflows).length} 条 Workflow。缺少信息的用例仍保留在草稿中。`);
    });
  }
  const changeStage = (next: typeof stage) => { setStage(next); setError(''); };
  return <div className="space-y-5" data-testid="document-import">
    <nav className="flex flex-wrap gap-2">{([['import', '1. 导入文档'], ['review', '2. 审查用例'], ['workflow', '3. 生成、保存与试跑']] as const).map(([id, name]) => <Button key={id} variant={stage === id ? 'secondary' : 'outline'} disabled={!!busy || id !== 'import' && !draft} onClick={() => changeStage(id)}>{name}</Button>)}</nav>
    {error && <p role="alert" className="whitespace-pre-wrap rounded-md border border-destructive/30 p-3 text-sm text-destructive">{error}</p>}
    {notice && <p role="status" className="rounded-md border p-3 text-sm">{notice}</p>}
    {busy && <div role="status" className="flex items-center gap-3 text-sm">{busy}…{request.current && <Button variant="outline" size="sm" onClick={() => void window.workspace.cancelImportPlan({ requestId: request.current! })}><Square />取消识别</Button>}</div>}
    <fieldset disabled={!!busy} className="space-y-5">{stage === 'import' && <section className="space-y-4 rounded-lg border bg-card p-5">
      <p className="text-sm">目标项目：{project.name}。导入和生成不会操作浏览器。</p>
      <div className="flex flex-wrap gap-4"><label className="space-y-2 text-sm"><span>目标 Suite</span><NativeSelect aria-label="文档目标 Suite" value={suiteId} onChange={event => setSuiteId(event.target.value)}>{project.suites.map(suite => <NativeSelectOption key={suite.id} value={suite.id}>{suite.name}</NativeSelectOption>)}<NativeSelectOption value="new">新建 Suite</NativeSelectOption></NativeSelect></label>{suiteId === 'new' && <Input aria-label="新 Suite 名称" value={newSuiteName} onChange={event => setNewSuiteName(event.target.value)} placeholder="新 Suite 名称" />}<label className="space-y-2 text-sm"><span>导入模式</span><NativeSelect aria-label="文档导入模式" value={mode} onChange={event => setMode(event.target.value as typeof mode)}><NativeSelectOption value="existing">导入已有测试用例</NativeSelectOption><NativeSelectOption value="design">根据需求 / 测试点设计用例</NativeSelectOption></NativeSelect></label></div>
      <p className="text-xs text-muted-foreground">已有用例模式保留原始步骤和预期。需求设计模式会生成建议，需确认推导内容与待补充问题。</p>
      <Textarea aria-label="Markdown 文档" className="min-h-72 font-mono text-xs" value={text} onChange={event => setText(event.target.value)} placeholder={'# 模块\n\n## [CASE-001] 用例标题\n- 前置条件：打开 ${baseUrl}\n- 步骤：\n  1. 点击文本“提交”\n- 预期结果：\n  - 页面显示“完成”'} />
      <div className="flex gap-3"><Button disabled={!!busy || !text.trim() || suiteId === 'new' && !newSuiteName.trim()} onClick={() => void act('正在解析文档', async () => accept(await window.workspace.parseImportDocument({ text, name: 'pasted.md' }))) }>解析 Markdown</Button><Button variant="outline" disabled={!!busy || suiteId === 'new' && !newSuiteName.trim()} onClick={() => void act('正在读取文档', async () => { const result = await window.workspace.pickImportDocument(); if (result) accept(result); })}><FileUp />上传 .md / .xmind</Button></div>
      {!!savedDrafts.length && <div className="space-y-2 border-t pt-4"><h3 className="text-sm font-medium">继续已保存的导入草稿</h3>{savedDrafts.map(snapshot => <Button key={snapshot.draft.id} variant="outline" className="mr-2" onClick={() => { setDraft(snapshot.draft); setRevision(snapshot.revision); setSelected(snapshot.draft.cases[0]?.id ?? ''); setStage('review'); }}>{snapshot.draft.document.name} · {snapshot.draft.cases.length} 条用例</Button>)}</div>}
    </section>}
    {stage !== 'import' && draft && <>
      <div className="flex flex-wrap gap-3"><Button variant="outline" disabled={!!busy || !variablesValid} onClick={() => void act('正在保存草稿', async () => { await persist(); setNotice('草稿已保存，重启后可继续处理。'); })}><Save />保存导入草稿</Button><Button variant="outline" disabled={!!busy} onClick={() => void act(draft.mode === 'design' ? 'AI 正在设计候选用例' : 'AI 正在识别候选用例', async () => {
        if (draft.cases.length && confirmGenerate !== 'plan') { setConfirmGenerate('plan'); setNotice('重新识别会替换当前用例草稿。请先保存草稿，再点击“确认重新识别”。'); return; }
        const requestId = crypto.randomUUID(); request.current = requestId;
        try { const result = await window.workspace.planImportDocument({ projectId: project.id, document: draft.document, mode: draft.mode, requestId }); const next = { ...draft, cases: result.cases, selectedIds: result.cases.map(item => item.id), workflows: {}, document: { ...draft.document, warnings: [...draft.document.warnings, ...result.warnings] } }; setDraft(next); setSelected(next.cases[0]?.id ?? ''); setConfirmGenerate(undefined); await persist(next); setNotice(`已识别 ${result.cases.length} 条候选用例，读取了 ${result.usedKnowledgeIds.length} 条知识。请审查后生成 Workflow。`); } finally { request.current = undefined; }
      })}><Sparkles />{confirmGenerate === 'plan' ? '确认重新识别' : draft.mode === 'design' ? 'AI 设计候选用例' : 'AI 识别自由格式'}</Button></div>
      <p className="text-xs text-muted-foreground">点击 AI 识别时，会向已配置模型发送本次文档、共享流程名称，以及 AI 选中的已确认知识正文。请使用变量引用，不要填写真实密码、Cookie 或 Token。</p>
      {draft.document.warnings.map((warning, index) => <p key={index} className="text-sm text-amber-700">{warning}</p>)}
      <div className="grid items-start gap-5 xl:grid-cols-[minmax(260px,0.8fr)_minmax(0,1.5fr)]">
        <aside className="space-y-4"><details open className="rounded-lg border bg-card p-4"><summary className="cursor-pointer text-sm font-medium">原文与来源</summary>{draft.document.tree ? <><div data-testid="xmind-source-tree" className="mt-3 max-h-96 overflow-auto"><SourceTree nodes={draft.document.tree} /></div><details className="mt-3"><summary className="text-xs">原始 content.json</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap break-words text-xs">{draft.document.text}</pre></details></> : <pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-words text-xs">{draft.document.text.split('\n').map((line, index) => `${index + 1}  ${line}`).join('\n')}</pre>}</details>
          <div className="space-y-2 rounded-lg border bg-card p-3">{draft.cases.map(item => <div key={item.id} className="flex items-center gap-2"><Checkbox aria-label={`选择用例 ${item.title}`} checked={draft.selectedIds.includes(item.id)} onCheckedChange={checked => setDraft({ ...draft, selectedIds: checked ? [...new Set([...draft.selectedIds, item.id])] : draft.selectedIds.filter(id => id !== item.id) })} /><Button variant={selected === item.id ? 'secondary' : 'ghost'} className="h-auto min-w-0 flex-1 justify-start whitespace-normal text-left" onClick={() => { setSelected(item.id); setConfirmGenerate(undefined); }}>{item.title || '未命名用例'}</Button></div>)}{!draft.cases.length && <p className="p-3 text-sm">未识别出明确用例边界，请使用 AI 识别。</p>}</div>
        </aside>
        <section className="min-w-0 space-y-4">{spec && <>
          <div className="flex flex-wrap gap-2"><Badge variant="outline">{sourceLabel(spec)}</Badge><Badge variant="secondary">{spec.origin === 'source' ? '原文' : spec.origin === 'ai' ? 'AI 建议' : '人工编辑'}</Badge><Badge variant="outline">{draft.saved[spec.id] ? '已保存资产，验证状态以试跑配置为准' : !spec.expectations.length ? '待补充' : '待验证'}</Badge></div>
          {stage === 'review' ? <div className="space-y-4 rounded-lg border bg-card p-5">
            <label className="block space-y-1 text-sm"><span>标题</span><Input aria-label="候选用例标题" value={spec.title} onChange={event => patch({ title: event.target.value })} /></label>
            <label className="block space-y-1 text-sm"><span>描述</span><Textarea aria-label="候选用例描述" value={spec.description} onChange={event => patch({ description: event.target.value })} /></label>
            <div className="grid gap-3 sm:grid-cols-3"><label className="space-y-1 text-sm"><span>优先级</span><NativeSelect aria-label="候选用例优先级" value={spec.priority} onChange={event => patch({ priority: event.target.value as CaseSpec['priority'] })}>{(['P0', 'P1', 'P2'] as const).map(priority => <NativeSelectOption key={priority} value={priority}>{priority}</NativeSelectOption>)}</NativeSelect></label><label className="space-y-1 text-sm"><span>分类路径（/ 分隔）</span><Input aria-label="候选用例分类" value={spec.path.join(' / ')} onChange={event => patch({ path: event.target.value.split('/').map(value => value.trim()).filter(Boolean) })} /></label><label className="space-y-1 text-sm"><span>标签（逗号分隔）</span><Input aria-label="候选用例标签" value={spec.tags.join(', ')} onChange={event => patch({ tags: event.target.value.split(/[,，]/).map(value => value.trim()).filter(Boolean) })} /></label></div>
            <h4 className="text-sm font-medium">前置条件</h4>{spec.preconditions.map((item, index) => <div key={item.id} className="space-y-2"><Badge variant="outline">{originLabel(item.origin)}</Badge><Textarea aria-label={`前置条件 ${index + 1}`} value={item.text} onChange={event => patch({ preconditions: spec.preconditions.map((row, at) => at === index ? { ...row, text: event.target.value, origin: 'manual', acknowledged: false } : row) })} /><NativeSelect aria-label={`前置条件类型 ${index + 1}`} value={item.kind} onChange={event => patch({ preconditions: spec.preconditions.map((row, at) => at === index ? { ...row, kind: event.target.value as typeof row.kind, origin: 'manual', acknowledged: false } : row) })}><NativeSelectOption value="check">执行前检查</NativeSelectOption><NativeSelectOption value="action">可执行准备</NativeSelectOption><NativeSelectOption value="manual">人工准备</NativeSelectOption></NativeSelect>{item.kind === 'manual' && <label className="flex gap-2 text-sm"><Checkbox checked={!!item.acknowledged} onCheckedChange={checked => patch({ preconditions: spec.preconditions.map((row, at) => at === index ? { ...row, acknowledged: checked === true } : row) })} />我已完成这项人工准备</label>}</div>)}
            <Button size="sm" variant="outline" onClick={() => patch({ preconditions: [...spec.preconditions, { id: crypto.randomUUID(), text: '', origin: 'manual', ref: spec.ref, kind: 'manual' }] })}>添加前置条件</Button>
            <h4 className="text-sm font-medium">测试数据</h4>{spec.data.map((item, index) => <div key={index} className="grid grid-cols-2 gap-2"><Input aria-label={`测试数据名称 ${index + 1}`} value={item.name} onChange={event => patch({ data: spec.data.map((row, at) => at === index ? { ...row, name: event.target.value, origin: 'manual' } : row) })} /><Input aria-label={`测试数据值 ${index + 1}`} value={item.value} onChange={event => patch({ data: spec.data.map((row, at) => at === index ? { ...row, value: event.target.value, origin: 'manual' } : row) })} /></div>)}
            <Button size="sm" variant="outline" onClick={() => patch({ data: [...spec.data, { name: '', value: '', origin: 'manual', ref: spec.ref }] })}>添加测试数据</Button>
            <h4 className="text-sm font-medium">操作步骤（按执行顺序）</h4>{spec.steps.map((item, index) => <div key={item.id} className="space-y-1"><span className="text-xs text-muted-foreground">{index + 1} · {item.origin === 'ai' ? 'AI 建议' : item.origin === 'manual' ? '人工编辑' : '原文'}</span><Textarea aria-label={`用例步骤 ${index + 1}`} value={item.text} onChange={event => patch({ steps: spec.steps.map((row, at) => at === index ? { ...row, text: event.target.value, origin: 'manual' } : row) })} /><NativeSelect aria-label={`操作步骤类型 ${index + 1}`} value={item.kind} onChange={event => patch({ steps: spec.steps.map((row, at) => at === index ? { ...row, kind: event.target.value as typeof row.kind, flowId: undefined, origin: 'manual' } : row) })}><NativeSelectOption value="action">操作</NativeSelectOption><NativeSelectOption value="wait">等待条件</NativeSelectOption><NativeSelectOption value="flow">共享流程</NativeSelectOption></NativeSelect>{item.kind === 'flow' && <NativeSelect aria-label={`共享流程 ${index + 1}`} value={item.flowId ?? ''} onChange={event => patch({ steps: spec.steps.map((row, at) => at === index ? { ...row, flowId: event.target.value || undefined, origin: 'manual' } : row) })}><NativeSelectOption value="">按步骤文字匹配流程名称</NativeSelectOption>{Object.entries(project.assets?.flows ?? {}).map(([id, flow]) => <NativeSelectOption key={id} value={id}>{flow.name}</NativeSelectOption>)}</NativeSelect>}<Button size="sm" variant="ghost" disabled={index === 0} onClick={() => { const steps = [...spec.steps]; [steps[index - 1], steps[index]] = [steps[index]!, steps[index - 1]!]; patch({ steps }); }}>上移步骤</Button><Button size="sm" variant="ghost" onClick={() => patch({ steps: spec.steps.filter((_, at) => at !== index), expectations: spec.expectations.map(expected => expected.afterStepId === item.id ? { ...expected, afterStepId: undefined, origin: 'manual' } : expected), questions: spec.expectations.some(expected => expected.afterStepId === item.id) ? [...spec.questions, { code: `deleted-step-${item.id}`, message: '已删除步骤对应的预期结果现放在全部操作后，请核对检查时机', blocks: 'generation' }] : spec.questions })}>删除步骤</Button></div>)}<Button size="sm" variant="outline" onClick={() => patch({ steps: [...spec.steps, { id: crypto.randomUUID(), text: '', origin: 'manual', ref: spec.ref, kind: 'action' }] })}>添加操作步骤</Button>
            <h4 className="text-sm font-medium">预期结果</h4>{spec.expectations.map((item, index) => <div key={item.id} className="space-y-2"><Badge variant="outline">{originLabel(item.origin)}</Badge><Textarea aria-label={`预期结果 ${index + 1}`} value={item.text} onChange={event => patch({ expectations: spec.expectations.map((row, at) => at === index ? { ...row, text: event.target.value, origin: 'manual' } : row) })} /><NativeSelect aria-label={`预期检查方式 ${index + 1}`} value={item.kind} onChange={event => patch({ expectations: spec.expectations.map((row, at) => at === index ? { ...row, kind: event.target.value as typeof row.kind, origin: 'manual' } : row) })}><NativeSelectOption value="text">可见文本断言</NativeSelectOption><NativeSelectOption value="semantic">AI 语义断言</NativeSelectOption></NativeSelect><NativeSelect aria-label={`检查时机 ${index + 1}`} value={item.afterStepId ?? ''} onChange={event => patch({ expectations: spec.expectations.map((row, at) => at === index ? { ...row, afterStepId: event.target.value || undefined, origin: 'manual' } : row) })}><NativeSelectOption value="">全部操作后</NativeSelectOption>{spec.steps.map((step, at) => <NativeSelectOption key={step.id} value={step.id}>步骤 {at + 1} 后</NativeSelectOption>)}</NativeSelect><Button size="sm" variant="ghost" onClick={() => patch({ expectations: spec.expectations.filter((_, at) => at !== index) })}>删除预期</Button></div>)}<Button size="sm" variant="outline" onClick={() => patch({ expectations: [...spec.expectations, { id: crypto.randomUUID(), text: '', origin: 'manual', ref: spec.ref, kind: 'semantic' }] })}>添加预期结果</Button>
            {spec.questions.map((question, index) => <label key={index} className="flex gap-2 text-sm"><Checkbox checked={!!question.resolved} onCheckedChange={checked => patch({ questions: spec.questions.map((row, at) => at === index ? { ...row, resolved: checked === true } : row) })} />已补充：{question.message}</label>)}
            <div className="flex flex-wrap gap-2 border-t pt-3"><Button variant="outline" size="sm" disabled={spec.steps.length < 2} onClick={() => { try { const parts = splitCaseSpec(spec, Math.ceil(spec.steps.length / 2), crypto.randomUUID()); parts[1].title += '（拆分）'; setDraft({ ...draft, cases: draft.cases.flatMap(item => item.id === spec.id ? parts : [item]), selectedIds: [...draft.selectedIds, parts[1].id] }); } catch (cause) { setError(String(cause)); } }}>从中间拆分用例</Button><Button variant="outline" size="sm" disabled={draft.selectedIds.length < 2} onClick={() => { try { const merged = mergeCaseSpecs(draft.cases.filter(item => draft.selectedIds.includes(item.id))); setDraft({ ...draft, cases: draft.cases.flatMap(item => item.id === merged.id ? [merged] : draft.selectedIds.includes(item.id) ? [] : [item]), selectedIds: [merged.id] }); setSelected(merged.id); } catch (cause) { setError(String(cause)); } }}>合并勾选的用例</Button><Button variant="outline" size="sm" onClick={() => { setDraft({ ...draft, cases: draft.cases.filter(item => item.id !== spec.id), selectedIds: draft.selectedIds.filter(id => id !== spec.id) }); setSelected(draft.cases.find(item => item.id !== spec.id)?.id ?? ''); }}>删除候选用例</Button></div>
          </div> : draft.workflows[spec.id] ? <WorkflowEditor key={spec.id} text={draft.workflows[spec.id]!.text} flows={project.assets?.flows} disabled={!!busy} onValidityChange={valid => setWorkflowValidity(current => current[spec.id] === valid ? current : { ...current, [spec.id]: valid })} onChange={value => setDraft({ ...draft, workflows: { ...draft.workflows, [spec.id]: { ...draft.workflows[spec.id]!, text: value, edited: true } } })} /> : <p className="rounded-lg border p-5 text-sm">此用例尚未生成 Workflow，请检查缺少的信息。</p>}
          {(issues[spec.id] ?? []).filter(issue => !issue.resolved).map((issue, index) => <p key={index} className="text-sm text-amber-700">{issue.blocks === 'generation' ? '生成前需补充' : '试跑前需补充'}：{issue.message}</p>)}
        </>}</section>
      </div>
      <section className="rounded-lg border bg-card p-5"><div className="mb-3 space-y-1">{[...new Set(Object.values(issues).flat().filter(issue => !issue.resolved && issue.code.startsWith('missing-variable-')).map(issue => issue.message))].map(message => <p key={message} className="text-sm text-amber-700">{message}</p>)}</div><VariableEditor label="本批用例公共变量" value={draft.variables} onValidityChange={setVariablesValid} onChange={variables => setDraft({ ...draft, variables })} disabled={!!busy} /><p className="mt-2 text-xs text-muted-foreground">这里统一补充共享输入；环境变量和运行时凭据可在试跑设置中提供。不要将密码或 Token 保存为字面量。</p></section>
      <div className="sticky bottom-0 flex flex-wrap items-center gap-3 border-t bg-background/95 py-4"><Button disabled={!!busy || !variablesValid || !draft.selectedIds.length} onClick={() => { if (draft.selectedIds.some(id => draft.workflows[id]) && confirmGenerate !== 'compile') { setConfirmGenerate('compile'); return; } void generate(); }}>{confirmGenerate === 'compile' ? '确认覆盖选中的 Workflow 并重新生成' : '生成选中的 Workflow'}</Button>{confirmGenerate === 'compile' && <p className="text-xs text-amber-700">这会替换选中用例的人工 Workflow 修改，其他用例保持不变。</p>}
        {stage === 'workflow' && <><NativeSelect aria-label="重复导入处理" value={duplicate} onChange={event => setDuplicate(event.target.value as typeof duplicate)}><NativeSelectOption value="skip">疑似重复：跳过</NativeSelectOption><NativeSelectOption value="copy">疑似重复：另存新用例</NativeSelectOption></NativeSelect><Button variant="outline" disabled={!!busy || !draft.selectedIds.length || draft.selectedIds.some(id => !draft.workflows[id] || workflowValidity[id] === false)} onClick={() => void act('正在校验并保存测试资产', async () => { const saved = await persist(); const result = await window.workspace.commitImportDraft({ projectId: project.id, id: saved.draft.id, revision: saved.revision, duplicate }); setDraft(result.snapshot.draft); setRevision(result.snapshot.revision); setNotice(`已保存 ${result.saved.length} 条用例，跳过 ${result.skipped.length} 条疑似重复用例。新资产均待验证。`); })}>保存选中测试资产</Button><Button variant="outline" disabled={!!busy || !draft.selectedIds.some(id => draft.saved[id])} onClick={() => onTrial(draft.selectedIds.flatMap(id => draft.saved[id] ? [draft.saved[id]!.caseId] : []))}>配置选中用例的试跑</Button><p className="w-full text-xs text-muted-foreground">保存不会执行页面操作。试跑设置会展示环境、会话、变量与操作；你确认启动后才会真实操作页面。文件存在不代表验证通过。</p></>}
      </div>
    </>}</fieldset>
  </div>;
}
